### ISSUE TITLE
Date picker plugin not working in iOS

### ISSUE THREAD

**Issue by brahmikumar** [rohanrhu/jquery.datepicker#1]
I integrated this plugin in my phonegap application, this plugin is working awsem in android,
 the problem is plugin not working in iOS version. when open page not showing anything shows only empty page.

Is this plugin supported for ios. Any way to implement this plugin in iOS version.

**Comment by rohanrhu** [comment]
Did you try it with safari in ios?

**Comment by rohanrhu** [comment]
Datepicker works in iOS. Probably there is another problem for iOS in your javascript.
